### ISSUE TITLE
BUG: Curve Corners Setting Not Working

### ISSUE THREAD

**Issue by dannymate** [DEM0NAssissan7/desktop-icons-neo#1]
`
        Prefs.desktopSettings.connect('changed', (obj, key) => {
            if (key == 'curved-corners') {
                this._showHidden = Prefs.desktopSettings.get_boolean('curved-corners');
                this._updateDesktop();
            }
        });
`
Should be:
`        
        Prefs.desktopSettings.connect('changed', (obj, key) => {
            if (key == 'curved-corners') {
                this._curvedCorners = Prefs.desktopSettings.get_boolean('curved-corners');
                this._updateDesktop();
            }
        });
`
desktopManager.js line 100.
I did try to create a pull request but it doesn't look like you've got them enabled. Pretty simple fix.

**Comment by DEM0NAssissan7** [comment]
Fixed in latest commit. Thanks for reporting the bug!
