### ISSUE TITLE
Gnome 3.36.9 - Double Icons

### ISSUE THREAD

**Issue by Smart-Helper** [DEM0NAssissan7/desktop-icons-neo#12]
I know the requirements are 3.38 but i have 3.36 and im not tech savvy enough to update to 3.38 because i dont know how much work i will have with my dozens of extensions.

So i currently have the problem that when i use this extension, that all my icons on the desktop appear twice. But only one "set" of them is usable the others seem to be burned into the background and only move whenever my desktop is refreshed (when i change some setting).

I disabled the Desktop Icons extension in GNOME Tweaks and have only this one enabled. I also rebooted. I also tried disabling anything desktop icon related, rebooting and then enabling only the neo extension.

Here is a video of it.

https://user-images.githubusercontent.com/38812603/139483812-d321ae9e-aa3f-4b85-9a42-9a6c2ebdbcb6.mp4

So i know that my version is not correct. So maybe someone knows how to fix that particular issue for gnome 3.36.9. If now i will keep using the old desktop icons. But i wouldnt want to because neo allowed me to get rid of those annoying arrow icons on every .desktop file

**Comment by DEM0NAssissan7** [comment]
I'll look into this issue. Stay posted if I need to ask some questions or have you do something.

**Comment by Smart-Helper** [comment]
im so sorry! i forgot to close this!

its fixed. Somehow the original ubuntu desktop icons extensions was still running even though i deactivated it. As soon as i purged all the files it worked perfectly fine!

Sorry again!
