### ISSUE TITLE
Gjs-CRITICAL error

### ISSUE THREAD

**Issue by Defatul** [DEM0NAssissan7/desktop-icons-neo#5]
Ubuntu 20.04.2 LTS
GNOME Shell 3.36.9

$ sudo journalctl --since "2 min ago" --no-pager -f

> Tem 29 13:58:42 xmodfool gnome-shell[2847]: Desktop Icons: Neo: 
>                                             (gjs:97058): Gjs-CRITICAL **: 13:58:42.959: JS ERROR: SyntaxError: expected expression, got '?' @ /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/dbusUtils.js:283
>                                             
>                                             (gjs:97058): Gjs-CRITICAL **: 13:58:42.959: Script /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/desktopicons-neo.js threw an exception
> Tem 29 13:58:44 xmodfool gnome-shell[2847]: Desktop Icons: Neo: 
>                                             (gjs:97076): Gjs-CRITICAL **: 13:58:44.078: JS ERROR: SyntaxError: expected expression, got '?' @ /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/dbusUtils.js:283
>                                             
>                                             (gjs:97076): Gjs-CRITICAL **: 13:58:44.078: Script /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/desktopicons-neo.js threw an exception
> Tem 29 13:58:45 xmodfool gnome-shell[2847]: Desktop Icons: Neo: 
>                                             (gjs:97088): Gjs-CRITICAL **: 13:58:45.201: JS ERROR: SyntaxError: expected expression, got '?' @ /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/dbusUtils.js:283
>                                             
>                                             (gjs:97088): Gjs-CRITICAL **: 13:58:45.201: Script /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/desktopicons-neo.js threw an exception
> Tem 29 13:58:46 xmodfool gnome-shell[2847]: Desktop Icons: Neo: 
>                                             (gjs:97104): Gjs-CRITICAL **: 13:58:46.326: JS ERROR: SyntaxError: expected expression, got '?' @ /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/dbusUtils.js:283
>                                             
>                                             (gjs:97104): Gjs-CRITICAL **: 13:58:46.326: Script /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/desktopicons-neo.js threw an exception
> Tem 29 13:58:47 xmodfool gnome-shell[2847]: Desktop Icons: Neo: 
>                                             (gjs:97117): Gjs-CRITICAL **: 13:58:47.460: JS ERROR: SyntaxError: expected expression, got '?' @ /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/dbusUtils.js:283
>                                             
>                                             (gjs:97117): Gjs-CRITICAL **: 13:58:47.460: Script /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/desktopicons-neo.js threw an exception
> Tem 29 13:58:48 xmodfool gnome-shell[2847]: Desktop Icons: Neo: 
>                                             (gjs:97127): Gjs-CRITICAL **: 13:58:48.582: JS ERROR: SyntaxError: expected expression, got '?' @ /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/dbusUtils.js:283
>                                             
>                                             (gjs:97127): Gjs-CRITICAL **: 13:58:48.582: Script /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/desktopicons-neo.js threw an exception
> Tem 29 13:58:49 xmodfool gnome-shell[2847]: Desktop Icons: Neo: 
>                                             (gjs:97142): Gjs-CRITICAL **: 13:58:49.704: JS ERROR: SyntaxError: expected expression, got '?' @ /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/dbusUtils.js:283
>                                             
>                                             (gjs:97142): Gjs-CRITICAL **: 13:58:49.704: Script /home/defatul/.local/share/gnome-shell/extensions/desktopicons-neo@darkdemon/desktopicons-neo.js threw an exception

**Comment by DEM0NAssissan7** [comment]
I will look into this issue. Does this specific error affect the function (perceived by the user) of the extension?

**Comment by DEM0NAssissan7** [comment]
After I looked into this problem a litlte further, it turns out that the 1.4 update uses new APIs that GNOME 3.34 doesn't support. I may have to remove GNOME 3.34 from the support list, or at least provide a modified version for the folks using Ubuntu 20.04. I may just have them use the old DI: Neo 1.3. It worked flawlessly on Ubuntu 20.04. I will close this issue and remove GNOME 3.34 from the support list. Thank you for reporting this issue!

**Comment by Defatul** [comment]
> Bu konuyu inceleyeceğim. Bu özel hata, uzantının işlevini (kullanıcı tarafından algılanan) etkiler mi?

not working at all
