### ISSUE TITLE
Extension using home foler instead of Desktop folder

### ISSUE THREAD

**Issue by marcelovbcfilho** [DEM0NAssissan7/desktop-icons-neo#6]
I recently installed the extension just for curiosity, I use openSUSE with the stock gnome setting wich doesn't include a desktop folder by default, so when I installed the extension, as the desktop I see all my home items, I think that should exists a way to the set which folder will be the desktop, to avoid problems like this.

SO: openSUSE Tumbleweed
Gnome: 40.3.0

Image showing that the extensions is using my home folder as desktop
![Screenshot from 2021-07-29 08-48-27](https://user-images.githubusercontent.com/51462138/127486783-677c2d83-19e4-44ef-a7e9-9796431e5849.png)

**Comment by DEM0NAssissan7** [comment]
On it. I'll add it as a menu setting. I have had people complain about this before, but I never thought to make the user set the desktop folder. Thank you!

**Comment by DEM0NAssissan7** [comment]
Added this feature in the latest build (2.0 BETA 2). Thank you so much for this feature request! I appreciate it a lot.

**Comment by marcelovbcfilho** [comment]
I've already installed the beta and it's working fine, thank you 😁.
