### ISSUE TITLE
Icon folders are 'copied'

### ISSUE THREAD

**Issue by byIlsa** [DEM0NAssissan7/desktop-icons-neo#9]
Hi all.

I installed the extension yesterday and drag/dropped some folders and file in some other folders.
Today, when I started my machine, I noticed that almost all folders where sort of duplicated.
One folder is greyed out and can't be opened.
I restarted to see if the problem persisted and unfortunately it did.
Ill include a screenshot of how it looks.

Linux distro:
OpenSuse Tumbleweed

Desktop environment:
Gnome (Wayland)

Any help would be greatly appreciated!
![Screenshot from 2021-08-12 09-00-31](https://user-images.githubusercontent.com/63145628/129152756-8dd3a673-5d38-4d4d-aaab-77c842ce7002.png)

**Comment by DEM0NAssissan7** [comment]
Can you send me a screenshot of the extensions that you have enabled? You may have 2 different desktop icons extensions running at the same time.

**Comment by byIlsa** [comment]
You were absolutely right! Where the icon extension I normally used was unavilable for a long time and I had deactivated it and installed Neo, I just saw that that same extension became build-in and both where showing.
Thanks!
